// Generated by LiveScript 1.4.0
(function(){
  var lodash, slice$ = [].slice;
  lodash = require('lodash');
  module.exports = lodash.assign({}, lodash, {
    lazy: function(f){
      var res;
      res = {};
      return function(){
        var args;
        args = slice$.call(arguments);
        if (res.promise) {
          return res.promise;
        } else {
          return res.promise = f.apply(this, args);
        }
      };
    },
    jsonError: function(error){
      var serializeError;
      serializeError = function(error){
        return {
          stack: error.stack,
          name: error.name,
          message: error.message
        };
      };
      switch (error.constructor) {
      case Error:
        return serializeError(error);
      default:
        return {
          name: error.constructor.name,
          message: String(error)
        };
      }
    },
    jsonQuery: function(string, object){}
  });
}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9ob21lL2xlc2gvY29kaW5nL3Jlc2JvdS9jb3JlL25vZGVfbW9kdWxlcy9sZXNoZGFzaC9pbmRleC5scyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7RUFFVyxNQUFBLENBQUEsQ0FBQSxDQUFBLE9BQUEsQ0FBQSxRQUFBO0VBR1gsTUFBTSxDQUFDLE9BQVEsQ0FBQSxDQUFBLENBQUUsTUFBTSxDQUFDLE9BQU8sSUFBSSxRQUNqQztJQUFBLE1BQU0sUUFBQSxDQUFBLENBQUE7O01BQ0YsR0FBSSxDQUFBLENBQUEsQ0FBRTthQUNOLFFBQUEsQ0FBQTs7UUFBSTtRQUNGLElBQUcsR0FBRyxDQUFDLE9BQVA7aUJBQW9CLEdBQUcsQ0FBQztTQUN4QjtpQkFBSyxHQUFHLENBQUMsT0FBUSxDQUFBLENBQUEsQ0FBRSxDQUFDLENBQUMsTUFBTSxNQUFHLElBQUg7Ozs7SUFJakMsV0FBVyxRQUFBLENBQUEsS0FBQTs7TUFDVCxjQUFlLENBQUEsQ0FBQSxDQUFFLFFBQUEsQ0FBQSxLQUFBO2VBQ2Y7VUFBQSxPQUFPLEtBQUssQ0FBQztVQUNiLE1BQU0sS0FBSyxDQUFDO1VBQ1osU0FBUyxLQUFLLENBQUM7UUFGZjs7TUFJRixRQUFPLEtBQUssQ0FBQyxXQUFiO0FBQUEsTUFDSSxLQUFBLEtBQUE7QUFBQSxlQUFTLGVBQWUsS0FBQTs7ZUFDWDtVQUFFLE1BQU0sS0FBSyxDQUFDLFdBQVcsQ0FBQztVQUFNLFNBQVMsT0FBTyxLQUFEO1FBQS9DOzs7SUFFbkIsV0FBVyxRQUFBLENBQUEsTUFBQSxFQUFBLE1BQUE7RUFsQlgsQ0FENkIiLCJzb3VyY2VzQ29udGVudCI6WyIjIGF1dG9jb21waWxlXG5cbnJlcXVpcmUhIHsgbG9kYXNoIH1cblxuXG5tb2R1bGUuZXhwb3J0cyA9IGxvZGFzaC5hc3NpZ24ge30sIGxvZGFzaCwgZG9cbiAgbGF6eTogKGYpIC0+XG4gICAgICByZXMgPSB7fVxuICAgICAgKC4uLmFyZ3MpIC0+XG4gICAgICAgIGlmIHJlcy5wcm9taXNlIHRoZW4gcmVzLnByb21pc2VcbiAgICAgICAgZWxzZSByZXMucHJvbWlzZSA9IGYuYXBwbHkgQCwgYXJnc1xuXG5cblxuICBqc29uRXJyb3I6IChlcnJvcikgLT5cbiAgICBzZXJpYWxpemVFcnJvciA9IChlcnJvcikgLT4gZG9cbiAgICAgIHN0YWNrOiBlcnJvci5zdGFja1xuICAgICAgbmFtZTogZXJyb3IubmFtZVxuICAgICAgbWVzc2FnZTogZXJyb3IubWVzc2FnZVxuICAgIFxuICAgIHN3aXRjaCBlcnJvci5jb25zdHJ1Y3RvclxuICAgICAgfCBFcnJvciA9PiBzZXJpYWxpemVFcnJvciBlcnJvclxuICAgICAgfCBvdGhlcndpc2UgPT4geyBuYW1lOiBlcnJvci5jb25zdHJ1Y3Rvci5uYW1lLCBtZXNzYWdlOiBTdHJpbmcoZXJyb3IpIH1cblxuICBqc29uUXVlcnk6IChzdHJpbmcsIG9iamVjdCkgLT5cbiAgICBcbiJdfQ==
